accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^shop$', views.shop, name='shop'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),

]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view, name='pagseguro_view'),
    url(r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view, name='paypal_view'),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(r'^notificacoes/pagseguro/$', views.pagseguro_notification, name='pagseguro_notification'),

]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobrenos/$', views.about, name='about'),
    url(r'^modelos/$', views.modelos, name='modelos'),
    url(r'^tecnologi/$', views.tecnologi, name='tecnologi'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'catalog:shop'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

checkout/models.py
# coding=utf-8
from pagseguro import PagSeguro

from django.db import models
from django.conf import settings
from catalog.models import Product

class CartItemManager(models.Manager): # Criando carrinho de compras

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists(): # SE JA EXISTE NÃO VOU CRIAR UM NOVO
            created = False # NÃO CRIA UM NOVO PRODUTO
            cart_item = self.get(cart_key=cart_key, product=product) # AI ELE PEGA O ID E O PRODUTO
            cart_item.quantity = cart_item.quantity + 1 # SÓ AUMENTA A SUA QUANTIDADE E SOMA MAIS 1
            cart_item.save() # E SALVA O PRODUTO
        else:
            created = True # SE NÃO ESTIVER, AI SIM ADCIONA UM PRODUTO NO CARRINHO
            cart_item = CartItem.objects.create(
                cart_key=cart_key, product=product, price=product.price
            )

        return cart_item, created

class CartItem(models.Model):

    cart_key = models.CharField(
        'Chave do Carrinho', max_length=40, db_index=True
    )
    product = models.ForeignKey('catalog.Product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)


    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)

    def subtotal(self):
        return self.price * self.quantity


class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product,
                price=cart_item.price
            )
        return order

class Order(models.Model):

    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
        ('deposito', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'Paypal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário')
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True
    )
    payment_option = models.CharField(
        'Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20,
        default='deposit'
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self): #Listando os pedidos
        product_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=product_ids)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'),
                output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']

    def pagseguro_update_status(self, status):
        if status == '3':
            self.status = 1
        elif status == '7':
            self.status = 2
        self.save()

    def complete(self):
        self.status = 1
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SENDBOX}
        )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = None
        pg.shipping = None
        pg.reference = self.pk
        for item in self.items.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )

        return pg

    def paypal(self):
        self.payment_option = 'paypal'
        self.save()
        paypal_dict = {
            'upload': '1',
            'business': settings.PAYPAL_EMAIL,
            'invoice': self.pk,
            'cmd': '_cart',
            'currency_code': 'BRL',
            'charset': 'utf-8',
        }
        index = 1
        for item in self.items.all():
            paypal_dict['amount_{}'.format(index)] = '%.2f' % item.price
            paypal_dict['item_name_{}'.format(index)] = item.product.name
            paypal_dict['quantity_{}'.format(index)] = item.quantity
            index = index + 1
        return paypal_dict


class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items')
    product = models.ForeignKey('catalog.Product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)


def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()


models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

checkout/views.py
# coding=utf-8
import logging
import json

from pagseguro import PagSeguro

from paypal.standard.forms import PayPalPaymentsForm
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received

from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    RedirectView, TemplateView, ListView, DetailView, View
)
from django.forms import modelformset_factory
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.conf import settings
from django.http import HttpResponse

from catalog.models import Product

from .models import CartItem, Order



logger = logging.getLogger('checkout.views')

# ADCIONA OS PRODUTOS NO CARRINHOS DE COMPRAS
class CreateCartItemView(View):

    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        logger.debug('Produto %s adicionado ao carrinho' % product)
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, product
        )

        if created:
            message = 'Produto adicionado com sucesso'
        else:
            message = 'Produto atualizado com sucesso'
        if request.is_ajax():
            return HttpResponse(
                json.dumps({'message': message}), content_type='application/javascript'
            )
        messages.success(request, message)
        return redirect('checkout:cart_item')




#CRIA VIZUALIZAÇÃO DO CARRINHO DE COMPRAS
class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem, fields=('quantity',), can_delete=True, extra=0
        )
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset



    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context


    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'),
                output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']



class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
            cart_items.delete() #remove os elementos do carrinho apos escolher forma de pagamento
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderDetailView(LoginRequiredMixin, DetailView): #Ira detalhar um determinado Objeto

    template_name = 'checkout/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class PagSeguroView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        pg = order.pagseguro()
        pg.redirect_url = self.request.build_absolute_uri(
            reverse('checkout:order_detail', args=[order.pk])
        )
        pg.notification_url = self.request.build_absolute_uri(
            reverse('checkout:pagseguro_notification')
        )

        response = pg.checkout()
        return response.payment_url

class PaypalView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/paypal.html'

    def get_context_data(self, **kwargs):
        context = super(PaypalView, self).get_context_data(**kwargs)
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        paypal_dict = order.paypal()
        paypal_dict['return_url'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['cancel_return'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['notify_url'] = self.request.build_absolute_uri(
            reverse('paypal-ipn')
        )

        context['form'] = PayPalPaymentsForm(initial=paypal_dict)
        return context

@csrf_exempt
def pagseguro_notification(request):
    notification_code = request.POST.get('notificationCode', None)
    if notification_code:
        pg = PagSeguro(
            email = settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SENDBOX}
        )
        notification_data = pg.check_notification(notification_code)
        status = notification_data.status
        reference = notification_data.reference
        try:
            order = Order.objects.get(pk=reference)
        except Order.DoesNotExist:
            pass
        else:
            order.pagseguro_update_status(status)
    return HttpResponde('OK')

def paypal_notification(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED and \
        ipn_obj.receiver_email == settings.PAYPAL_EMAIL:
        try:
            order = Order.objects.get(pk=ipn_obj.invoice)
            order.complete()
        except Order.DoesNotExist:
            pass


valid_ipn_received.connect(paypal_notification)

create_cartitem = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()
pagseguro_view = PagSeguroView.as_view()
paypal_view = PaypalView.as_view()

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% load static %}
{% block title %}
Finalização da Compra
{% endblock %}

{% block container %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/checkout.css' %}">


<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'catalog:shop' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'index' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu">
                {% for category in categories %}
                <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category }}</a> {% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:index' %}">Conta</a></li>
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Registro</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}">
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->
  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'catalog:shop' %}">Home</a><i>|</i></li>
        <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a><i>|</i></li>
        <li class="active">Finalização da Compra</li>
      </ul>
    </div>
  </div>
  <!-- //banner_inner -->
</div>
<!-- top Products -->
<div class="ads-grid_shop">
  <div class="shop_inner_inf">
    <div class="privacy about">
      <h3>Escolha a forma de <span>Pagamento</span></h3>
      <!--/tabs-->
      <div class="responsive_tabs">
        <div id="horizontalTab">
          <ul class="resp-tabs-list">

            <li>Pagar com PagSeguro</li>
            <li>Pagar com Paypal </li>
          </ul>
          <div class="resp-tabs-container">

            <div class="tab1">
              <div class="pay_info">
                <div class="col-md-6 tab-grid">
                  <img class="pp-img" src="{% static 'assets/images/pagSeguro01.jpg' %}" alt="Image Alternative text" title="PagSeguro">
                  <p>Importante: Você será redirecionado para o site do PagSeguro para concluir seu pagamento com segurança.</p><a href="{% url 'checkout:pagseguro_view' order.pk %}" class="btn btn-success">Pagar via PagSeguro</a>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
            <div class="tab2">
              <div class="pay_info">
                <div class="col-md-6 tab-grid">
                  <img class="pp-img" src="{% static 'assets/images/paypal.png' %}" alt="Image Alternative text" title="PayPal">
                  <p>Importante: Você será redirecionado para o site do PayPal para concluir seu pagamento com segurança.</p><a href="{% url 'checkout:paypal_view' order.pk %}" class="btn btn-primary">Pagar via Paypal</a>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--//tabs-->
    </div>

  </div>
  <!-- //payment -->

  <div class="clearfix"></div>
</div>
{% endblock %}

{% block scripts %}

<script src="{% static 'assets/js/jquery.flexslider.js' %}"></script>
<script src="{% static 'assets/js/easy-responsive-tabs.js' %}"></script>
	<script>
		$(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default', //Types: default, vertical, accordion
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				activate: function (event) { // Callback function if tab is switched
					var $tab = $(this);
					var $info = $('#tabInfo');
					var $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
			$('#verticalTab').easyResponsiveTabs({
				type: 'vertical',
				width: 'auto',
				fit: true
			});
		});
	</script>

<!-- credit-card -->
<script type="text/javascript" src="{% static 'assets/js/creditly.js' %}"></script>
<link rel="stylesheet" href="{% static 'assets/css/creditly.css' %}" type="text/css" media="all" />

<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
<script type="text/javascript">
  $(function () {
    var creditly = Creditly.initialize(
      '.creditly-wrapper .expiration-month-and-year',
      '.creditly-wrapper .credit-card-number',
      '.creditly-wrapper .security-code',
      '.creditly-wrapper .card-type');

    $(".creditly-card-form .submit").click(function (e) {
      e.preventDefault();
      var output = creditly.validate();
      if (output) {
        // Your validated credit card output
        console.log(output);
      }
    });
  });
</script>
<!-- //credit-card -->

{% endblock%}

checkout/templates/checkout/order_detail.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% block title %}
  Pedido #{{ order.pk }}
{% endblock %}

{% block accounts_container %}
  <h2>Pedido #{{ order.pk }}</h2>
  <dl class="row dl-horizontal">
    <dt>Total R$</dt>
    <dd>{{ object.total|floatformat:"2" }}</dd>
    <dt>Situação</dt>
    <dd>{{ object.get_status_display }}</dd>
    <dt>Data</dt>
    <dd>{{ object.created|date:"d/m/y H:i"}}</dd>
    <dt>Meio de Pagamento</dt>
    <dd>{{ object.get_payment_option_display }}</dd>
  </dl>
  <h3>Itens do Pedido</h3>
  {% for item in object.items.all %}
    <dl class="row dl-horizontal">
      <dt>Produto</dt>
      <dd>{{ item.product }}</dd>
      <dt>Quantidade</dt>
      <dd>{{ item.quantity }}</dd>
      <dt>Preço</dt>
      <dd>R$ {{ item.price|floatformat:"2"}}</dd>
    </dl>
  {% endfor %}
{% endblock%}

checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% block title %}
  Meus Pedidos
{% endblock %}

{% block accounts_container %}
  <h2>Meus Pedidos</h2>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Produtos</th>
        <th>Situação</th>
        <th>Data</th>
      </tr>
    </thead>
    <tbody>
      {% for order in object_list %}
        <tr>
          <td>
            <a href="{% url 'checkout:order_detail' order.pk %}">#{{ order.pk }}</a>
          </td>
          <td>
          {% for product in order.products %}
              {{ product.name }}{% if not forloop.last %}<br /> {% endif %}
          {% endfor%}
          </td>
          <td>
            {{ order.get_status_display }}
          </td>
          <td>
            {{ order.created|date:"d/m/y"}}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% pagination request paginator page_obj %}
{% endblock %}

checkout/templates/checkout/paypal.html
{% extends "base.html" %}

{% block title %}
Pagamento via Paypal
{% endblock %}

{% block container %}
<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'catalog:shop' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'index' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu">
                {% for category in categories %}
                <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category }}</a> {% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:index' %}">Conta</a></li>
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Registro</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}">
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->
  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'catalog:shop' %}">Home</a><i>|</i></li>
        <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a><i>|</i></li>
        <li class="active">Pagamento via Paypal</li>>
      </ul>
    </div>
  </div>
  <!-- //banner_inner -->
</div>

<div class="container">
    <div class="page-header">
        <h1>Você está sendo redirecionado para o paypal</h1>
    </div>
    <div id="paypal" class="row">
        {{ form.render }}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function(){
        $("#paypal form").submit();
    });
</script>
{% endblock %}