accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^shop$', views.shop, name='shop'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),

]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view, name='pagseguro_view'),
    url(r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view, name='paypal_view'),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(r'^notificacoes/pagseguro/$', views.pagseguro_notification, name='pagseguro_notification'),

]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobrenos/$', views.about, name='about'),
    url(r'^modelos/$', views.modelos, name='modelos'),
    url(r'^tecnologi/$', views.tecnologi, name='tecnologi'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'catalog:shop'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
         'Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    cpf = models.CharField('CPF', max_length=11, unique=True)
    email = models.EmailField('E-mail', unique=True)
    telefone = models.CharField('Telefone', max_length=11, blank=True)
    cep = models.CharField('CEP', max_length=11, blank=True)
    city = models.CharField('Cidade', max_length=100)
    adress = models.CharField('Endereço', max_length=150)
    number = models.IntegerField('Nº')
    complement = models.CharField('Complemento', max_length=200)

    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['cpf', 'email', 'telefone']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'cpf', 'email', 'telefone', 'cep', 'city', 'adress', 'number', 'complement']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'cpf', 'email', 'name', 'telefone', 'cep', 'city', 'adress', 'number', 'complement', 'is_active', 'is_staff']

accounts/views.py
# coding=utf-8

from django.shortcuts import render
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import login as auth_login

from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email', 'telefone', 'cep',  'city', 'adress', 'number']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'catalog:shop' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'accounts:index' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu" >
        				{% for category in categories %}
        				<a class="dropdown-item"  href="{{ category.get_absolute_url }}">{{ category }}</a>
        				{% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>
            <li><a href="{% url 'catalog:shop' %}">Loja Virtual</a></li>
             {% if user.is_authenticated %}
             <li><a href="{% url 'logout' %}">Sair</a></li>
             {% else %}
             <li><a href="{% url 'login' %}">Entrar</a></li>
             <li><a href="{% url 'accounts:register' %}">Registro</a></li>
             {% endif %}
         </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}" >
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->


  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'accounts:index' %}">Início</a><i>|</i></li>
        <li class="active">Minha Conta</li>

      </ul>
    </div>
  </div>
  <!-- //banner_inner -->
</div>

<div class="ads-grid_shop">
  <div class="shop_inner_inf">

  <div class="row">
      <div class="col-md-4">
          <div class="list-group">
            <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
            <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
            <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
            <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
          </div>
      </div>
      <div class="col-md-8">
          {% block accounts_container %}
              <h2>Bem vindo {{ user }}</h2>
          {% endblock %}
      </div>
  </div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "registerbase.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="body"></div>
<div class="grad"></div>
<div class="header">

  <div ><a class="navbar-brand" href="{% url 'index' %}"><span>Dudu</span><i>Shoes</i></a></div>

</div>
<br>


        <form class=" login" method="post">

             <div class="page-header">
                 <h1>Cadastro de Usuário</h1>
             </div>

            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="sizefull s-text7 p-l-22 p-r-22">
                    {% render_field field class="loginInput" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}


                <button type="submit" class="buttonRegister" >Cadastrar</button>
                
            </fieldset>
          </form>

  <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}