accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register'),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^shop$', views.shop, name='shop'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),

]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view, name='pagseguro_view'),
    url(r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view, name='paypal_view'),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(r'^notificacoes/pagseguro/$', views.pagseguro_notification, name='pagseguro_notification'),

]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from core import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobrenos/$', views.about, name='about'),
    url(r'^modelos/$', views.modelos, name='modelos'),
    url(r'^tecnologi/$', views.tecnologi, name='tecnologi'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'catalog:shop'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalog/models.py
# coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

    order = models.IntegerField(default=0)
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['order']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)
    size = models.CharField('Tamanho', max_length=100, null=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    image = models.ImageField(
        'Image', upload_to='products', blank=True, null=True
    )
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

    def numeros(self):
        return self.size.split(",")


class ProductImages (models.Model):
    product = models.ForeignKey(Product, default=None, related_name='images')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__ (self):
        return self.product.name

    class Meta:
        verbose_name = 'Imagem Produto'
        verbose_name = 'Imagens do produto'

catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.db import models
from django.views.decorators.cache import cache_page

from watson import search as watson

from .models import Product, Category


class ProductListView(generic.ListView):

    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset

product_list = ProductListView.as_view()



class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product
    }
    return render(request, 'catalog/product.html', context)

class ShopView(generic.ListView):
    template_name = 'catalog/shop.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset


shop = ShopView.as_view()

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}

<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'index' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'index' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu" >
        				{% for category in categories %}
        				<a class="dropdown-item"  href="{{ category.get_absolute_url }}">{{ category }}</a>
        				{% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>

             {% if user.is_authenticated %}
             <li><a href="{% url 'logout' %}">Sair</a></li>
             {% else %}
             <li><a href="{% url 'login' %}">Entrar</a></li>
             <li><a href="{% url 'accounts:register' %}">Registro</a></li>
             {% endif %}
         </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}" >
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->


  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'index' %}">Home</a><i>|</i></li>
        <li>produtos</li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="page-header">
      <h3>{{ current_category }}</h3>
  </div>
    {% for product in product_list %}
      {% include "catalog/_product.html" %}
    {% endfor %}
    {% pagination request paginator page_obj %}

</div>



{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% load static %}
{% load thumbnail %}
{% load pagination %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}

<link rel="stylesheet" href="{% static 'assets/css/style01.css' %}" type="text/css" media="screen" property="" />
<!-- banner -->
<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'index' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'catalog:shop' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu" >
        				{% for category in categories %}
        				<a class="dropdown-item"  href="{{ category.get_absolute_url }}">{{ category }}</a>
        				{% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>

             {% if user.is_authenticated %}
             <li><a href="{% url 'logout' %}">Sair</a></li>
             {% else %}
             <li><a href="{% url 'login' %}">Entrar</a></li>
             <li><a href="{% url 'accounts:register' %}">Registro</a></li>
             {% endif %}
         </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}" >
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->


  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'index' %}">Home</a><i>|</i></li>
        <li>Produto</li>
      </ul>
    </div>
  </div>
</div>
  <!-- //banner_inner -->


<!-- top Products -->
	<div class="ads-grid_shop">
		<div class="shop_inner_inf">
			<div class="col-md-4 single-right-left ">
				<div class="grid images_3_of_2">
					<div class="flexslider">

						<ul class="slides">
              {% for image in product.images.all %}
				        {% thumbnail image.image "500x500"  upscale=False as thumb %}
  							<li data-thumb="{{ thumb.url }}">
  								<div class="thumb-image">
                    <img src="{{ thumb.url }}" data-imagezoom="true" class="img-responsive">
                  </div>
  							</li>
              {% endfor %}
						</ul>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<div class="col-md-8 single-right-left simpleCart_shelfItem">
				<h3>{{product}}</h3>
				<p><span class="item_price">R${{product.price}}</span>
					<del>$1,199</del>
				</p>

          <div class="product-options">
              <ul class="size-option">
                <li><span class="text-uppercase">Tamanho:</span></li>
                  {% for number in product.numeros %}
                    <li><a href="#">{{ number }}</a></li>
                  {% endfor %}
              </ul>
            </div>

            <div class="single_page">
              <h6>Descrição do produto</h6>
              <a href="#description"><p>{{ product.description|truncatewords:"25"|linebreaks  }} </p></a>
            </div>

        <div class="container">
          <div class="row">
            <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-success " role="button"><i class="fa fa-cart-plus"></i> COMPRAR</a>

          </div>
        </div>
        <br>
				<ul class="social-nav model-3d-0 footer-social social single_page">
					<li class="share">Compartilhar: </li>
					<li>
						<a href="https://www.facebook.com/" class="facebook">
							<div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
							<div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
						</a>
					</li>
					<li>
						<a href="https://twitter.com" class="twitter">
							<div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
							<div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
						</a>
					</li>
					<li>
						<a href="https://www.instagram.com" class="instagram">
							<div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
							<div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
						</a>
					</li>
					<li>
						<a href="https://br.pinterest.com" class="pinterest">
							<div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
							<div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
						</a>
					</li>
				</ul>

			</div>
			<div class="clearfix"></div>
			<!--/tabs-->
			<div class="responsive_tabs">
				<div id="horizontalTab">
					<ul class="resp-tabs-list">
						<li id='description'>DESCRIÇÃO</li>
						<li>TECNOLOGIA</li>
						<li>iNFORMAÇÃO</li>
					</ul>
					<div class="resp-tabs-container">
						<!--/tab_one-->
						<div class="tab1">

							<div class="single_page">
								<h6>Descrição do produto</h6>
								<p>{{ product.description|linebreaks }} </p>
							</div>
						</div>
						<!--//tab_one-->
						<div class="tab2">

							<div class="single_page">
								<div class="bootstrap-tab-text-grids">
									<div class="bootstrap-tab-text-grid">
										<div class="bootstrap-tab-text-grid-left">
											<img src="{% static 'assets/images/slideTecnologia' %}.jpg" alt=" " class="img-responsive">
										</div>
										<div class="bootstrap-tab-text-grid-right">
											<ul>
												<li><a href="#">Tecnologia utilizada</a></li>
												<li><a href="#"><i class="fa fa-reply-all" aria-hidden="true"></i>VOLTAR</a></li>
											</ul>
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget.Ut enim ad minima veniam,
												quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis
												autem vel eum iure reprehenderit.</p>
										</div>
										<div class="clearfix"> </div>
									</div>
								</div>
							</div>
						</div>
						<div class="tab3">

							<div class="single_page">
								<h6>{{ product }}</h6>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie
									blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt
									ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore
									magna aliqua.</p>
								<p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie
									blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt
									ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore
									magna aliqua.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--//tabs-->
			<!-- /new_arrivals -->
			<div class="new_arrivals">
				<h3>produtos em destaque</h3>
        <div class="product-sec1">
          <!--/mens-->


        </div>


				<div class="clearfix"></div>
			</div>


			<!--//new_arrivals-->


		</div>
	</div>
	<!-- //top products -->
{% endblock %}


{% block scripts %}

<script src="{% static 'assets/js/imagezoom.js' %}"></script>
<script src="{% static 'assets/js/jquery.flexslider.js' %}"></script>
<script src="{% static 'assets/js/easy-responsive-tabs.js' %}"></script>

<script>
		$(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default', //Types: default, vertical, accordion
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				activate: function (event) { // Callback function if tab is switched
					var $tab = $(this);
					var $info = $('#tabInfo');
					var $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
			$('#verticalTab').easyResponsiveTabs({
				type: 'vertical',
				width: 'auto',
				fit: true
			});
		});
	</script>


<script>
    // Can also be used with $(document).ready()
    $(window).load(function () {
      $('.flexslider').flexslider({
        animation: "slide",
        controlNav: "thumbnails"
      });
    });
  </script>
<script type="text/javascript">
   jQuery(document).ready(function ($) {
     $(".scroll").click(function (event) {
       event.preventDefault();
       $('html,body').animate({
         scrollTop: $(this.hash).offset().top
       }, 1000);
     });
   });
 </script>

 <script type="text/javascript">
   $(function() {
     $('.cart-item-add').on('click', function(e) {
       e.preventDefault();
       $.ajax({
         url: $(this).attr('href'),
         dataType: 'json',
         success: function(data, textStatus, jqXHR) {
           alert(data.message);
         }
       });
     });
   });
 </script>


 {% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'index' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'index' %}" class="active">Home</a></li>
            <li><a href="{% url 'about' %} ">About</a></li>
            <li><a href="404.html">Sobre nós</a></li>
            <li><a href="{% url 'catalog:shop'  %} ">Loja Vitual</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>
          </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}" >
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->
  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'index' %}">Home</a><i>|</i></li>
        <li>Carrinho</li>
      </ul>
    </div>
  </div>
  <!-- //banner_inner -->
</div>

  <div class="new_arrivals">
    <div class="container">
    <div class="m-text5 t-center">
        <h3>Mais Produtos</h3>
    </div>
    <div class="row">
        {% for product in products %}
          {% include "catalog/_product.html" %}
        {% endfor %}
    </div>
    {% pagination request paginator page_obj %}
    </div>
  </div>
    <!-- Pagination -->


{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function(){
    $('.cart-item-add').on('click', function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('href'),
            dataType: 'json',
            success: function(data, textStatus, jqXHR){
                alert(data.message);
            }
        });
    });
});
</script>
{% endblock %}

catalog/templates/catalog/shop.html
{% extends "base.html" %}
{% load static %}

{% load pagination %}
{% block title %} Shop | {{ block.super }} {% endblock %}


{% block container %}
<!-- banner -->
<div class="banner_top innerpage" id="home">
  <div class="wrapper_top_w3layouts">
    <div class="header_agileits">
      <div class="logo inner_page_log">
        <h1><a class="navbar-brand" href="{% url 'catalog:shop' %}"><span>DUDU</span> <i>Shoes</i></a></h1>
      </div>
      <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
          <ul>
            <li><a href="{% url 'catalog:shop' %}" class="active">Home</a></li>
            <li class="nav-item dropdown">
              <a class="nav-lin dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}">Categorias <span class="caret"></span></a>
              <div class="dropdown-menu" >
        				{% for category in categories %}
        				<a class="dropdown-item"  href="{{ category.get_absolute_url }}">{{ category }}</a>
        				{% endfor %}
              </div>
            </li>
            <li><a href="{% url 'about' %} ">Sobre nós</a></li>
            <li><a href="{% url 'contact' %} ">Contato</a></li>

             {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:index' %}">Minha Conta</a></li>
             <li><a href="{% url 'logout' %}">Sair</a></li>
             {% else %}
             <li><a href="{% url 'login' %}">Entrar</a></li>
             <li><a href="{% url 'accounts:register' %}">Registro</a></li>
             {% endif %}
         </ul>
        </nav>
      </div>
      <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
      </div>
      <!-- cart details -->
      <div class="top_nav_right">
        <div class="shoecart shoecart2 cart cart box_1">
          <a href="{% url 'checkout:cart_item' %}">
							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
					</a>
        </div>
      </div>
    </div>
  </div>
  <!-- //cart details -->
  <!-- search -->
  <div class="search_w3ls_agileinfo">
    <div class="cd-main-header">
      <ul class="cd-header-buttons">
        <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
      </ul>
    </div>
    <div id="cd-search" class="cd-search">
      <form action="{% url 'catalog:product_list' %}" >
        <input name="q" type="text" placeholder="Pesquisar...">
      </form>
    </div>
  </div>
  <!-- //search -->
  <div class="clearfix"></div>
  <!-- /banner_inner -->


  <div class="services-breadcrumb_w3ls_agileinfo">
    <div class="inner_breadcrumb_agileits_w3">

      <ul class="short">
        <li><a href="{% url 'catalog:shop' %}">Home</a><i>|</i></li>
        <li>Loja Virtual</li>
      </ul>
    </div>
  </div>
  <!-- //banner_inner -->
</div>
<!-- top Products -->
<div class="ads-grid_shop">
  <div class="shop_inner_inf">


    <div class="left-ads-display col-md-12">
      <div class="wrapper_top_shop">
        <div class="col-md-6 shop_left">
          <img src="{% static 'assets/images/banner3.jpg' %}" alt="">
          <h6>Nike</h6>
        </div>
        <div class="col-md-6 shop_right">
          <img src="{% static 'assets/images/banner2.jpg' %}" alt="">
          <h6>Adidas</h6>
        </div>
        <div class="clearfix"></div>
        <!-- product-sec1 -->
        <div class="product-sec1">
          <!--/mens-->
          {% for product in products %}
           {% include "catalog/_product.html" %}
          {% endfor %}

          {% pagination request paginator page_obj %}

        </div>

        <!-- //product-sec1 -->
        <div class="col-md-6 shop_left shp">
          <img src="{% static 'assets/images/banner4.jpg' %}" alt="">
          <h6>Sapatos</h6>
        </div>
        <div class="col-md-6 shop_right shp">
          <img src="{% static 'assets/images/banner1.jpg' %}" alt="">
          <h6>Chuteiras</h6>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>


  </div>
</div>

{% endblock %}


{% block scripts %}



<script type="text/javascript">
  $(function() {
    $('.cart-item-add').on('click', function(e) {
      e.preventDefault();
      $.ajax({
        url: $(this).attr('href'),
        dataType: 'json',
        success: function(data, textStatus, jqXHR) {
          alert(data.message);
        }
      });
    });
  });
</script>
{% endblock %}